### ISSUE TITLE
A small example produces a result I didn't expect

### ISSUE THREAD

**Issue by bontaq** [i-am-tom/holmes#14]
Hello, big fan of your library and it seems very cool.  I'm trying it out with this years advent of code, and ran into this while doing the first problem.  Boiled down, basically:

```
test :: IO (Maybe [ Defined Int ])
test = do
  let guesses = 2 `from` [1, 3]

  guesses `satisfying` \[a, b] -> and'
    [ (a .+ b) .== 5 ]
```
returns `Just [Exactly 1,Exactly 4]`, where as I would've expected it to fail without a match.

I'm guessing I'm using something wrong but was surprised.  Thanks again for your library!

**Comment by i-am-tom** [comment]
Yikes! I think you're right that this shouldn't happen. At a guess, I'd say that for whatever reason, `b` isn't getting assigned a value, and so back-propagating `5 - 1` is then filling it in. I'll have a look at this over the weekend (I'm actually part way through a pretty thorough rewrite of some of the internals) and see if I can sort it out :)

Thanks so much for the report - this is definitely a weird one! 🕵️
